apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev-roadrunner-project
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: Roadrunner project for DEV environment

  sourceRepos:  
  - 'https://github.com/radoscis-org/argo-poc.git'
  - 'https://radoscis-org.github.io/helm-charts-poc'
  
  destinations:
    - server: https://kubernetes.default.svc
      name: in-cluster
      namespace: roadrunner-dev    
  

  clusterResourceWhitelist:
  - group: ''
    kind: Namespace

  namespaceResourceBlacklist:
  - group: ''
    kind: ResourceQuota
  - group: ''
    kind: LimitRange
  - group: ''
    kind: NetworkPolicy

  # Deny all namespaced-scoped resources from being created, except for Deployment and StatefulSet
  namespaceResourceWhitelist:
  - group: 'apps'
    kind: Deployment
  - group: 'apps'
    kind: StatefulSet  
  - group: ''
    kind: Configmap
  - group: ''
    kind: Service

  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: true

  roles:
  # A role which provides read-only access to all applications in the project
  - name: read-only
    description: Read-only privileges to my-project
    policies:
    - p, proj:dev-roadrunner-project:read-only, applications, get, dev-roadrunner-project/*, allow
    groups:
    - my-oidc-group

  # By default, apps may sync to any cluster specified under the `destinations` field, even if they are not
  # scoped to this project. Set the following field to `true` to restrict apps in this cluster to only clusters
  # scoped to this project.
  # permitOnlyProjectScopedClusters: true

  # When using Applications-in-any-namespace, this field determines which namespaces this AppProject permits
  # Applications to reside in. Details: https://argo-cd.readthedocs.io/en/stable/operator-manual/app-any-namespace/
  sourceNamespaces:
  - "argocd-roadrunner-dev"