apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-argocd-roadrunner
  namespace: argocd-roadrunner-dev
  labels:
    name: roadrunner
    env: dev
spec:  
  project: dev-roadrunner-project
  source:
    chart: roadrunner          
    repoURL: https://radoscis-org.github.io/helm-charts-poc
    targetRevision: 1.0.0
    helm:
      releaseName: roadrunner      
      ignoreMissingValueFiles: false
      skipCrds: true  
  destination:
    # cluster API URL
    server: https://kubernetes.default.svc    
    namespace: roadrunner-dev
  info:
    - name: 'Roadrunner Environment'
      value: 'dev'      
  # Sync policy
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:     
    - CreateNamespace=true 
